### ISSUE TITLE
Your BIMserver does not seem to have a working outgoing internet connection?

### ISSUE THREAD

**Issue by dslwz2008** [opensourceBIM/BIMserver#581]
I am using bimserverjar-1.5.76.jar . I double click the jar file and start server successfully. Then click "Launch Webbrowser" and enter setup page. The outputs of the last step are as follows:

Setting up...
	Setting up admin account...
		Admin account successfully setup
	Skipping email setup...
	Checking internet connection _from_ your BIMserver...
		Your BIMserver does not seem to have a working outgoing internet connection.
	Not installing extended data schemas because there is no internet connection
	Not installing plugins because there is no internet connection

Setup successful, refresh to go to the status page

I have tried many times and I do have a internet connection, but it always reports that "Your BIMserver does not seem to have a working outgoing internet connection." So what's the problem?

**Comment by studentMa** [comment]
The BIMserver installation can be installed directly through jar or through Tomcat. In any case, the corresponding port number must be set. If the extranet needs access, please open the port

**Comment by dslwz2008** [comment]
The default port number 8082 was used. I have tried to stop my firewall on my OS(win10), but it still doesn't work. The http://localhost:8082 can be accessed, but the extended data schemas and plugins can't be installed.

**Comment by studentMa** [comment]
建议使用tomcat进行项目发布，灵活配置端口，如果是插件自动安装失败请确保本地网络可以流畅访问外网，否则下载极慢很可能安装失败。

**Comment by dslwz2008** [comment]
我试了使用tomcat，bimserverjar-1.5.76.war被自动解压开，通过网址进行配置，在setup那一步的时候，出现的信息和上面一样。在独立IP的服务器上也试了，还是没有成功......

**Comment by QuintinWu** [comment]
So have you got a feasible way to the problem? I've also encountered this one but found nothing to do with it. Even though I tried the solution that you can install these plugins by hand, an annoying exception occurred》

**Comment by dslwz2008** [comment]
@QuintinWu I didn't solve the problem yet. I also tried to install these plugins manually following this wiki (https://github.com/opensourceBIM/BIMserver/wiki/Installing-without-internet-connection). However, when I open bimviews page (http://localhost:8082/apps/bimviews/), there is only "_Loading BIMviews..._" appear. I decide to try it later and wish next version will be OK.

**Comment by studentMa** [comment]
这是我这边发布成功的项目，版本有点老但一样使用，现在分享给你，无需安装直接发布即可浏览，具体看内部教程。链接: http://pan.baidu.com/s/1i5mmVCL 密码: kf82

**Comment by dslwz2008** [comment]
谢谢，我再试试。我注意到这个项目已经发展了好几年，但是不知道为什么产品还是不够成熟稳定，文档也比较老了。我在网上搜过，BIM这个行业算是比较小众，商业软件也不是很多，opensourceBIM也算是为数不多的BIM开源解决方案之一，我个人觉得这个行业用户群体应该越来越大。

**Comment by fyqspy** [comment]
你好，可以再分享下吗，学习下，我目前也是start server successfully，have a working outgoing internet connection

**Comment by studentMa** [comment]
http://pan.baidu.com/s/1kUIzczl

**Comment by Lemonlee8** [comment]
@studentMa 下载试了下，一直是loading状态。。。。
![image](https://user-images.githubusercontent.com/7747035/30577725-b398b01c-9d42-11e7-9391-248b1363a865.png)

**Comment by mydev04** [comment]
参考这个，本地上传插件，https://github.com/opensourceBIM/BIMserver/wiki/Outgoing-internet-connection

**Comment by TamJW** [comment]
主要问题是这样：
安装时会直接访问http://localhost:8082 获取各种json，问题是本机上哪有什么东西给他获取啊……
![image](https://user-images.githubusercontent.com/10151366/31419188-f3cea426-ae6c-11e7-8e42-99e69ba7187e.png)

那个本地上传插件的按钮也没有出现 
![image](https://user-images.githubusercontent.com/10151366/31419172-db67f7ca-ae6c-11e7-80ca-795bdbf84f15.png)

**Comment by rubendel** [comment]
Fixed in GIT, will be in new release.

**Comment by maakkoush** [comment]
Hi,

Am getting same error with version 1.5.182. The port is not blocked as per network team and the machine has Internet connection. PLease advise.

**Comment by maakkoush** [comment]
Hi Ruben, am still facing the same described issue above with the latest release. I tried to install the plugins offline, but same issue. Nothing is found in the logs. 
Plz advise.

**Comment by maakkoush** [comment]
upon reinstalling the plugins offline am getting this error although am installing the dependencies along with it as per the link.
Installing uploaded plugin bimviews-0.0.184.jar
		Failed to collect dependencies at org.opensourcebim:pluginbase:jar:1.5.182
